### PR TITLE
feature: setup jest and an example integration test

### PR DESCRIPTION
**Pull request by thetutlage**
FIXES: FRMW-2682

This PR adds support for testing in the starter kit. It uses `jest` alongside `@swc/jest` to run the TypeScript files as it is without creating a build.

Also, I have added the `.env.test` file which is loaded before the app is booted and hence it can override environment variables from the `.env` file. This is helpful when you want to use different ENV vars for your tests without modifying the same `.env` file.

---

The `integration:http` test has been created this pings the `/health` endpoint and asserts for a 200 response.

There are also npm scripts for other types of tests like the **unit tests**, **integration:modules**, **integration:e2e**. However, no example test files have been created for them. Do you guys have any suggestions for the same tests under these suites?

---

**Side note**: What's the difference between `integration:e2e` and `integration:http` suite?

### CODE REVIEW

**Comment by thetutlage** [comment]
I have just added a couple of packages and that has resulted in a massive diff in the `yarn.lock` file. Maybe that is something to do with my yarn version? I am using `v4.4.0`

**Review by shahednasser — COMMENTED** [review]
I do agree with you that I don't see the reason to have `http` and `e2e`, but otherwise this looks good!

**Review by adrien2p — APPROVED** [review]

**Comment by thetutlage** [comment]
@shahednasser What's the version of yarn you are using with the starter?

**Comment by shahednasser** [comment]
@thetutlage v1, although it's updated every three hours by an action (see [example PR](https://github.com/medusajs/medusa-starter-default/pull/1669))

**Comment by shahednasser** [comment]
@thetutlage just FYI I'm holding off merging new preview updates to not cause conflicts in your PR, or can we merge it in?

**Comment by thetutlage** [comment]
Feel free to merge them. Ill resolve conflicts.

Btw, do you have any idea why one of the CI checks are failing?

**Comment by shahednasser** [comment]
Pnpm is still not working, Carlos will be working on it when he has the time

**Review by shahednasser — APPROVED** [review]

**Pull request merged**
