### PR TITLE
chore: update packages and imports

### PR DESCRIPTION
**Pull request by thetutlage**
Let's wait for the latest release before we merge this

### CODE REVIEW

**Comment by carlos-r-l-rodrigues** [comment]
should we also update the `tsconfig` to change the module to `node16`?

**Comment by thetutlage** [comment]
@carlos-r-l-rodrigues  Just checked. Seems to be `Node16` already. https://github.com/medusajs/medusa-starter-default/blob/feat/v2/tsconfig.json

**Comment by carlos-r-l-rodrigues** [comment]
@thetutlage my bad, I wasn't in the correct branch.
Thanks

**Review by olivermrbl — APPROVED** [review]

**Review by adrien2p — APPROVED** [review]
Should we add the include to the tsconfig

**Pull request merged**
